//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HudsonLimaAteliware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reposit
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<byte> hasDownloads { get; set; }
        public Nullable<byte> hasIssues { get; set; }
        public string htmlURL { get; set; }
        public string Language { get; set; }
        public Nullable<int> Stars { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> InseridoNoBD { get; set; }
    }
}
